"""V3 Stage 4 statistics: hybrid (variant chosen on seeds 100-109) vs tuned tripod, tuned tripod without connectome (h_none = tuned tripod + same healing wrapper) and PPO.
Seeds 0-9 only. Paired by eval seed; 100,000-resample percentile bootstrap, rng seed 12345; Holm across the cells of each comparison.
Verdict rule per cell (stated before looking at final data): if either arm has a fall in that cell, compare paired SURVIVAL TIME (t_end; censored at scenario length), else compare distance. WIN if the 95% CI of (hybrid - other) is above 0, LOSS if below 0, TIE if it includes 0.
PPO arm = mean over the 5 training seeds (ppo, ppo_s1..s4) of each eval seed's value; for cells where only training seed 0 exists (fault_sequential+healing, healthy+healing) the arm is PPO seed 0 only and is flagged."""
import glob

import numpy as np
import pandas as pd

from stats_v2_helpers import paired, wilson

fin = pd.concat([pd.read_json(f, lines=True) for f in glob.glob("results/v3_stage4_final_0-9.jsonl")])
base = pd.concat([pd.read_json(f, lines=True) for f in glob.glob("results/v2_*_0-9.jsonl")]).drop_duplicates(["controller", "scenario", "seed"], keep="last")
base = base[base.seed.between(0, 9)]
cells = ["flat", "rough1", "rough3", "push", "slope10", "slope15", "slope20", "fault_disable_leg+healing", "fault_lock_joint+healing", "fault_sensor_dropout+healing", "fault_sequential+healing", "healthy+healing"]
main = sorted(fin.variant.unique())
hyb = "h_half_pg"


def arm(kind, cell):
    if kind in ("h_half_pg", "h_none"):
        g = fin[(fin.variant == kind) & (fin.scenario == cell)]
    elif kind == "tuned":
        g = base[(base.controller == "tuned_tripod") & (base.scenario == cell)]
    else:
        g = base[base.controller.isin(["ppo", "ppo_s1", "ppo_s2", "ppo_s3", "ppo_s4"]) & (base.scenario == cell)]
        n_tr = g.controller.nunique()
        g = g.groupby("seed").agg(distance=("distance", "mean"), t_end=("t_end", "mean"), fell=("fell", "sum"), mean_speed=("mean_speed", "mean")).reset_index()
        g["n_train"] = n_tr
    return g.sort_values("seed")


md = ["# V3 Stage 4: hybrid vs tuned tripod vs PPO (seeds 0-9, simulation, 2 vCPU sandbox). Generated by scripts/stage4_stats_v3.py", "",
      f"Hybrid = variant `{hyb}`: tuned-tripod pitch feedback (kp=1.2) + healing layer + connectome speed/freq nudges x0.5 and turn nudge x1, nudges gated off when the low-passed |pitch| > 0.10 rad or after the first fault suspicion. `h_none` = same wrapper with all nudges 0 (tuned tripod + healing).", "",
      "| cell | arm | falls/10 (Wilson) | mean survival s | mean distance m | speed err m/s |", "|---|---|---|---|---|---|"]
for c in cells:
    for k in ("h_half_pg", "h_none", "tuned", "ppo"):
        g = arm(k, c)
        if not len(g): continue
        kf = float(g.fell.sum()) if k != "ppo" else float(g.fell.sum()) / max(int(g.n_train.iloc[0]), 1)
        n = 10
        lo, hi = wilson(round(kf), n)
        spd = (g.mean_speed - 0.25).abs().mean()
        tag = k + (f" (n_train={int(g.n_train.iloc[0])}, falls/10 averaged)" if k == "ppo" else "")
        md.append(f"| {c} | {tag} | {kf:.1f}/10 ({lo:.2f}-{hi:.2f}) | {g.t_end.mean():.2f} | {g.distance.mean():.3f} | {spd:.4f} |")
rows = []
for other in ("tuned", "h_none", "ppo"):
    for c in cells:
        a, b = arm(hyb, c), arm(other, c)
        if len(a) != 10 or len(b) != 10: continue
        any_fall = (a.fell.sum() + b.fell.sum()) > 0
        col = "t_end" if any_fall else "distance"
        p = paired(a[col].to_numpy(), b[col].to_numpy())
        pd_ = paired(a.distance.to_numpy(), b.distance.to_numpy())
        verdict = "WIN" if p["lo"] > 0 else "LOSS" if p["hi"] < 0 else "TIE"
        rows.append((other, c, col, p, pd_, verdict))
md += ["", "## Paired comparisons (hybrid minus other); verdict by the pre-stated rule", "", "| other | cell | metric used | diff [95% CI] | distance diff m [95% CI] | verdict |", "|---|---|---|---|---|---|"]
for other, c, col, p, pd_, v in rows:
    md.append(f"| {other} | {c} | {col} | {p['diff']:+.3f} [{p['lo']:+.3f}, {p['hi']:+.3f}] | {pd_['diff']:+.3f} [{pd_['lo']:+.3f}, {pd_['hi']:+.3f}] | {v} |")
cnt = {}
for other, c, col, p, pd_, v in rows: cnt.setdefault(other, {}).setdefault(v, 0); cnt[other][v] += 1
md += ["", "Win/tie/loss counts over cells: " + "; ".join(f"vs {o}: {d}" for o, d in cnt.items())]
open("docs/v3_stage4_tables.md", "w").write("\n".join(md) + "\n")
print("\n".join(md[-20:]))
