"""V3 Stage 1: per-cell primary metrics for every controller, seeds 0-9 only (reads results/v2_*_0-9.jsonl, no new runs).
Metrics: falls/10 with Wilson 95%; time-to-fall (t_end of fallen episodes; survival time = t_end for all episodes, censored at the scenario length when no fall);
speed-tracking error |mean_speed - 0.25 m/s| (command speed 0.25); distance. Distance rewards walking faster than commanded, so it is secondary.
Healing effect (paired by seed) on disable_leg: falls and survival-time difference with a 100,000-resample paired bootstrap, percentile 95%, rng seed 12345."""
import glob

import numpy as np
import pandas as pd

from stats_v2_helpers import paired, wilson

frames = [pd.read_json(f, lines=True) for f in sorted(glob.glob("results/v2_*_0-9.jsonl"))]
df = pd.concat(frames).drop_duplicates(["controller", "scenario", "seed"], keep="last")
df = df[df.seed.between(0, 9)].copy()
df["spd_err"] = (df.mean_speed - 0.25).abs()
cells = ["flat", "rough1", "rough3", "push", "slope10", "slope15", "slope20", "fault_disable_leg", "fault_disable_leg+healing", "fault_lock_joint", "fault_lock_joint+healing", "fault_sensor_dropout", "fault_sensor_dropout+healing", "fault_reduce_torque", "fault_reduce_torque+healing", "fault_sequential", "fault_sequential+healing", "healthy+healing"]
ctrls = ["tripod", "tuned_tripod", "connectome", "shuffled", "random_graph", "filter", "mlp", "ppo"]
md = ["# V3 Stage 1 tables (seeds 0-9, simulation, 2 vCPU sandbox). Generated by scripts/stage1_v3.py", "",
      "Columns: falls/10 (Wilson 95%); mean survival time s (t_end; = scenario length if no fall; censored); mean time-to-fall s among fallen episodes (n); speed error = mean |mean_speed - 0.25| m/s; distance m. 'ppo' = training seed 0 only.", "",
      "| cell | controller | falls/10 (Wilson) | mean survival s | time-to-fall s (n fallen) | speed err m/s | distance m |", "|---|---|---|---|---|---|---|"]
for s in cells:
    for c in ctrls:
        g = df[(df.controller == c) & (df.scenario == s)]
        if len(g) != 10: continue
        k = int(g.fell.sum()); lo, hi = wilson(k, 10)
        ttf = f"{g[g.fell].t_end.mean():.2f} ({k})" if k else "-"
        md.append(f"| {s} | {c} | {k}/10 ({lo:.2f}-{hi:.2f}) | {g.t_end.mean():.2f} | {ttf} | {g.spd_err.mean():.4f} | {g.distance.mean():.3f} |")
md += ["", "## Healing effect on a single disabled leg (paired by seed, with minus without healing)", "", "| controller | falls no-heal | falls heal | survival-time diff s [95% CI] | distance diff m [95% CI] |", "|---|---|---|---|---|"]
for c in ["tripod", "tuned_tripod", "connectome", "ppo"]:
    a = df[(df.controller == c) & (df.scenario == "fault_disable_leg+healing")].sort_values("seed")
    b = df[(df.controller == c) & (df.scenario == "fault_disable_leg")].sort_values("seed")
    if len(a) == 10 and len(b) == 10:
        ps = paired(a.t_end.to_numpy(), b.t_end.to_numpy()); pd_ = paired(a.distance.to_numpy(), b.distance.to_numpy())
        md.append(f"| {c} | {int(b.fell.sum())}/10 ({wilson(int(b.fell.sum()), 10)[0]:.2f}-{wilson(int(b.fell.sum()), 10)[1]:.2f}) | {int(a.fell.sum())}/10 ({wilson(int(a.fell.sum()), 10)[0]:.2f}-{wilson(int(a.fell.sum()), 10)[1]:.2f}) | {ps['diff']:+.2f} [{ps['lo']:+.2f}, {ps['hi']:+.2f}] | {pd_['diff']:+.3f} [{pd_['lo']:+.3f}, {pd_['hi']:+.3f}] |")
open("docs/v3_stage1_tables.md", "w").write("\n".join(md) + "\n")
print("\n".join(md[-8:]))
