"""Stage 5 statistics for v2. Reads results/v2_*.jsonl (seeds 0-9 only). Writes results/v2_stats.json and docs/v2_tables.md.
Old v1 ci95 (scripts/make_report.py): Student-t 95% half-width = t_{0.975,n-1} * sd(ddof=1)/sqrt(n) of the per-seed values, n=10.
v2: paired bootstrap on per-seed differences (same seed in both arms), 10,000 resamples of the 10 differences, percentile 95% CI, rng seed 12345.
Two-sided bootstrap p = 2*min(P(boot_mean<=0), P(boot_mean>=0)) floored at 1/(B+1); Holm step-down across each comparison family.
Falls: k/10 with Wilson 95% interval. Effect size: mean paired difference in metres and Cohen's d_z (mean diff / sd of diffs)."""
import glob
import json

import numpy as np
import pandas as pd

B = 10_000
rng = np.random.default_rng(12345)
frames = [pd.read_json(f, lines=True) for f in sorted(glob.glob("results/v2_ablation_0-9.jsonl") + glob.glob("results/v2_rebench_0-9.jsonl") + glob.glob("results/v2_tuned_0-9.jsonl") + glob.glob("results/v2_pposeeds_0-9.jsonl"))]
df = pd.concat(frames).drop_duplicates(["controller", "scenario", "seed"], keep="last")
df = df[df.seed.between(0, 9)]


def wilson(k, n, z=1.96):
    p = k / n; d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d; h = z * np.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return max(0.0, c - h), min(1.0, c + h)


def paired(a, b):
    d = np.asarray(a) - np.asarray(b)
    bs = rng.choice(d, (B, len(d)), replace=True).mean(1)
    lo, hi = np.percentile(bs, [2.5, 97.5])
    p = max(2 * min((bs <= 0).mean(), (bs >= 0).mean()), 1 / (B + 1))
    dz = d.mean() / d.std(ddof=1) if d.std(ddof=1) > 0 else float("nan")
    return dict(diff=float(d.mean()), lo=float(lo), hi=float(hi), p=float(p), dz=float(dz), n=len(d))


def holm(ps):
    order = np.argsort(ps); m = len(ps); adj = np.zeros(m); run = 0.0
    for r, i in enumerate(order):
        run = max(run, (m - r) * ps[i]); adj[i] = min(1.0, run)
    return adj


def vec(c, s, col="distance"):
    g = df[(df.controller == c) & (df.scenario == s)].sort_values("seed")
    return g[col].to_numpy(), g.seed.to_numpy()


out = {"bootstrap_resamples": B, "ci_method": "percentile, paired by seed", "families": {}}
md = ["# v2 tables (seeds 0-9, 2 vCPU sandbox, simulation). Generated by scripts/stats_v2.py", ""]
cells_all = sorted(df.scenario.unique())
ctrls = sorted(df.controller.unique())
md.append("## Per-cell means, falls (Wilson 95%)\n\n| cell | controller | mean distance m | falls/N (Wilson) |\n|---|---|---|---|")
for s in cells_all:
    for c in ctrls:
        x, _ = vec(c, s)
        if not len(x): continue
        g = df[(df.controller == c) & (df.scenario == s)]
        k, n = int(g.fell.sum()), len(g); lo, hi = wilson(k, n)
        md.append(f"| {s} | {c} | {x.mean():.3f} | {k}/{n} ({lo:.2f}-{hi:.2f}) |")


def family(name, ref, others, cells):
    rows = []
    for o in others:
        for s in cells:
            a, sa = vec(ref, s); b, sb = vec(o, s)
            if len(a) == 10 and len(b) == 10 and (sa == sb).all():
                r = paired(a, b); r.update(ref=ref, other=o, cell=s); rows.append(r)
    if rows:
        adj = holm(np.array([r["p"] for r in rows]))
        for r, a in zip(rows, adj): r["p_holm"] = float(a)
    out["families"][name] = rows
    md.append(f"\n## {name}: {ref} minus other, paired bootstrap 95% CI, Holm-adjusted p\n\n| cell | other | diff m | 95% CI | d_z | p (raw) | p (Holm) |\n|---|---|---|---|---|---|---|")
    for r in rows:
        md.append(f"| {r['cell']} | {r['other']} | {r['diff']:+.3f} | [{r['lo']:+.3f}, {r['hi']:+.3f}] | {r['dz']:+.2f} | {r['p']:.4f} | {r['p_holm']:.4f} |")


abl = [c for c in ctrls if c in ("shuffled", "random_graph", "filter")]
family("A. ablations (connectome vs ablation)", "connectome", abl, ["flat", "rough1", "rough3", "push", "slope10", "fault_disable_leg+healing", "fault_lock_joint+healing", "fault_sensor_dropout+healing"])
base = [c for c in ctrls if c in ("tripod", "ppo")]
family("B. baselines (connectome vs tripod/PPO)", "connectome", base, cells_all)
nud = df[df.nudge_speed_gain_absdev.notna()].groupby("controller")[["nudge_speed_gain_absdev", "nudge_freq_scale_absdev", "nudge_turn_abs", "nudge_stance_abs"]].mean()
md.append("\n## Mean nudge magnitude applied to the CPG (per control step, all episodes)\n\n| variant | mean abs(speed_gain-1) | mean abs(freq_scale-1) | mean abs(turn) | mean abs(stance) |\n|---|---|---|---|---|")
for c, r in nud.iterrows():
    md.append(f"| {c} | {r.nudge_speed_gain_absdev:.4f} | {r.nudge_freq_scale_absdev:.4f} | {r.nudge_turn_abs:.4f} | {r.nudge_stance_abs:.4f} |")
# POST-HOC (not pre-registered): distance rewards walking faster than the 0.25 m/s target; speed-tracking error |mean_speed - 0.25| (flat/rough cells, no fall)
md.append("\n## POST-HOC, not pre-registered: speed tracking error |mean speed - 0.25 m/s| (m/s), flat/rough cells\n\n| cell | controller | mean speed | mean abs error |\n|---|---|---|---|")
for s_ in ["flat", "rough1", "rough3"]:
    for c in ctrls:
        g = df[(df.controller == c) & (df.scenario == s_)]
        if len(g): md.append(f"| {s_} | {c} | {g.mean_speed.mean():.4f} | {(g.mean_speed - 0.25).abs().mean():.4f} |")
json.dump(out, open("results/v2_stats.json", "w"), indent=1)
open("docs/v2_tables.md", "w").write("\n".join(md) + "\n")
print("\n".join(md[-60:]))
